[package]
name = "lan_party_monitor_client"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
local-ip-address = "0.6"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.33"
tauri = { version = "2.5.1", features = [] }
tokio = { version = "1.43", features = ["macros", "net", "rt-multi-thread", "time"] }
uuid = { version = "1.11", features = ["serde", "v4"] }
